const columns = [
  'First Name',
  'Last Name',
  'Date of Employment',
  'Date of Birth',
  'Phone',
  'Email',
  'Department',
  'Position',
  'Actions',
];

const data = [
  {
    firstName: 'John',
    lastName: 'Doe',
    dateOfEmployment: '2022-01-01',
    dateOfBirth: '1990-01-01',
    phone: '123-456-7890',
    email: '',
    department: 'Engineering',
    position: 'Software Engineer',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    dateOfEmployment: '2021-06-15',
    dateOfBirth: '1985-05-20',
    phone: '987-654-3210',
    email: '',
    department: 'Marketing',
    position: 'Marketing Manager',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    dateOfEmployment: '2020-03-10',
    dateOfBirth: '1992-11-30',
    phone: '555-123-4567',
    email: '',
    department: 'Sales',
    position: 'Sales Representative',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Bob',
    lastName: 'Brown',
    dateOfEmployment: '2019-08-25',
    dateOfBirth: '1988-02-15',
    phone: '444-987-6543',
    email: '',
    department: 'HR',
    position: 'HR Manager',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Charlie',
    lastName: 'Davis',
    dateOfEmployment: '2023-02-28',
    dateOfBirth: '1995-07-10',
    phone: '222-333-4444',
    email: '',
    department: 'Finance',
    position: 'Financial Analyst',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Eve',
    lastName: 'Wilson',
    dateOfEmployment: '2022-11-05',
    dateOfBirth: '1993-12-25',
    phone: '111-222-3333',
    email: '',
    department: 'IT',
    position: 'System Administrator',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'David',
    lastName: 'Martinez',
    dateOfEmployment: '2021-04-18',
    dateOfBirth: '1987-09-12',
    phone: '666-777-8888',
    email: '',
    department: 'Customer Support',
    position: 'Support Specialist',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Grace',
    lastName: 'Garcia',
    dateOfEmployment: '2020-07-22',
    dateOfBirth: '1994-03-05',
    phone: '333-444-5555',
    email: '',
    department: 'Operations',
    position: 'Operations Manager',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Frank',
    lastName: 'Martinez',
    dateOfEmployment: '2018-09-30',
    dateOfBirth: '1986-04-20',
    phone: '888-999-0000',
    email: '',
    department: 'Legal',
    position: 'Legal Advisor',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Hannah',
    lastName: 'Lopez',
    dateOfEmployment: '2023-01-15',
    dateOfBirth: '1991-10-10',
    phone: '777-888-9999',
    email: '',
    department: 'Research',
    position: 'Research Scientist',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Michael',
    lastName: 'Hernandez',
    dateOfEmployment: '2022-12-01',
    dateOfBirth: '1989-06-18',
    phone: '555-666-7777',
    email: '',
    department: 'Design',
    position: 'Graphic Designer',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Sophia',
    lastName: 'Clark',
    dateOfEmployment: '2021-05-20',
    dateOfBirth: '1990-08-30',
    phone: '444-555-6666',
    email: '',
    department: 'Product',
    position: 'Product Manager',
    actions: 'Edit | Delete',
  },
  {
    firstName: 'Liam',
    lastName: 'Lewis',
    dateOfEmployment: '2020-10-10',
    dateOfBirth: '1992-02-28',
    phone: '333-444-5555',
    email: '',
    department: 'Quality Assurance',
    position: 'QA Engineer',
    actions: 'Edit | Delete',
  },
];

export {columns, data};
